language: cpp
dist: trusty
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get install -y cmake libboost-dev libnuma-dev libaio-dev libhwloc-dev libatlas-base-dev zlib1g-dev numactl
compiler:
- g++
script:
- sudo python setup.py install
- python flashpy/test.py
